server:
  port: 8082

spring:
  datasource:
    driver-class-name: jdbc:mysql://mysql:3306/movies_db
    url: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Service